name: Build, Test, and Deploy Node.js App

on:
 # push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm install
      working-directory: ./node-app

    # Run tests with Mocha
    - name: Run Mocha tests
      run: npm test
      working-directory: ./node-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Checkout the repository again
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Deploy the ARM template
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: <YourResourceGroup>
        template: ./node-app/azuredeploy.json
        parameters: <YourParameters>

    # Optional: Output any deployment result
    - name: Show deployment outputs
      run: echo "Deployment completed successfully"
